"""FaceNet Recognizer using keras-facenet package

This recognizer uses the pip-installable keras-facenet package which
auto-downloads pre-trained weights from MS-Celeb-1M dataset.
"""

import numpy as np
import cv2
from typing import Optional, Dict, Any
from pathlib import Path
import logging

try:
    from keras_facenet import FaceNet as KerasFaceNet

    KERAS_FACENET_AVAILABLE = True
except ImportError:
    KERAS_FACENET_AVAILABLE = False

from bp_face_recognition.vision.recognition.base import (
    BaseRecognizer,
    EmbeddingMetadata,
)

logger = logging.getLogger(__name__)


class FaceNetKerasRecognizer(BaseRecognizer):
    """
    FaceNet recognizer using keras-facenet package.

    Pre-trained on MS-Celeb-1M dataset, produces 512-dimensional
    L2-normalized face embeddings.

    This is the RECOMMENDED recognizer for production use.
    """

    def __init__(
        self,
        model_path: Optional[str] = None,  # Not used, kept for API compatibility
        input_size: tuple = (160, 160),
        normalize: bool = True,
    ):
        """
        Initialize FaceNet recognizer.

        Args:
            model_path: Ignored (keras-facenet auto-downloads weights)
            input_size: Expected input image size (height, width)
            normalize: Whether to normalize pixel values
        """
        if not KERAS_FACENET_AVAILABLE:
            raise ImportError(
                "keras-facenet is required. Install with: uv pip install keras-facenet"
            )

        super().__init__(input_size, normalize)

        self.embedding_size = 512

        # Load FaceNet model (auto-downloads weights on first use)
        try:
            logger.info("Loading FaceNet model (keras-facenet)...")
            self.model = KerasFaceNet()
            self._initialized = True
            logger.info("FaceNet model loaded successfully (512D embeddings)")
        except Exception as e:
            logger.error(f"Failed to load FaceNet model: {e}")
            self.model = None
            self._initialized = False

    def get_embedding(self, face_image: np.ndarray) -> np.ndarray:
        """
        Extract 512D face embedding using FaceNet.

        Args:
            face_image: Input face image array (BGR format)

        Returns:
            512-dimensional embedding vector (L2 normalized)
        """
        if not self._validate_face_image(face_image):
            return np.array([])

        if self.model is None:
            logger.error("FaceNet model not loaded")
            return np.array([])

        try:
            # Preprocess: BGR to RGB, resize to 160x160
            face_rgb = cv2.cvtColor(face_image, cv2.COLOR_BGR2RGB)
            face_resized = cv2.resize(face_rgb, self.input_size)

            # Add batch dimension: (1, 160, 160, 3)
            face_batch = np.expand_dims(face_resized, axis=0)

            # Extract embedding
            embedding = self.model.embeddings(face_batch)

            # Flatten to 1D vector
            embedding = embedding.flatten()

            # Validate output
            if not self._validate_embedding(embedding):
                logger.warning("Invalid embedding generated by FaceNet")
                return np.array([])

            return embedding

        except Exception as e:
            logger.error(f"Face embedding extraction failed: {e}")
            return self._handle_recognition_error(e, "get_embedding")

    def get_embedding_with_metadata(self, face_image: np.ndarray) -> EmbeddingMetadata:
        """
        Extract embedding with metadata.

        Args:
            face_image: Input face image

        Returns:
            EmbeddingMetadata with embedding and metadata
        """
        import time

        start_time = time.time()
        embedding = self.get_embedding(face_image)
        processing_time = time.time() - start_time

        confidence = 1.0 if len(embedding) > 0 else 0.0

        return EmbeddingMetadata(
            embedding=embedding,
            confidence=confidence,
            processing_time=processing_time,
            face_quality=self._estimate_face_quality(face_image),
        )

    def _estimate_face_quality(self, face_image: np.ndarray) -> float:
        """
        Estimate face quality based on image characteristics.

        Args:
            face_image: Input face image

        Returns:
            Quality score between 0.0 and 1.0
        """
        try:
            if len(face_image.shape) < 2:
                return 0.0

            # Check image sharpness (variance of Laplacian)
            gray = cv2.cvtColor(face_image, cv2.COLOR_BGR2GRAY)
            laplacian = cv2.Laplacian(gray, cv2.CV_64F)
            sharpness = np.var(laplacian)

            # Normalize sharpness to [0, 1]
            quality_score = min(sharpness / 1000.0, 1.0)

            return max(quality_score, 0.1)

        except Exception:
            return 0.5  # Default quality

    def get_recognizer_info(self) -> Dict[str, Any]:
        """
        Get information about the recognizer.

        Returns:
            Dictionary with recognizer metadata
        """
        info = super().get_recognizer_info()
        info.update(
            {
                "model_type": "FaceNet-InceptionResNetV1",
                "embedding_size": self.embedding_size,
                "input_size": self.input_size,
                "preprocessing": {
                    "normalize": self.normalize,
                    "color_conversion": "BGR_to_RGB",
                    "resize_method": "bilinear",
                },
                "training_dataset": "MS-Celeb-1M",
                "package": "keras-facenet",
            }
        )

        return info

    def verify_model(self) -> Dict[str, Any]:
        """
        Verify the loaded model by running a test prediction.

        Returns:
            Dictionary with verification results
        """
        if not self._initialized:
            return {"verified": False, "error": "Model not initialized"}

        try:
            # Create a dummy face image
            dummy_face = np.random.randint(0, 255, (160, 160, 3), dtype=np.uint8)

            # Test embedding extraction
            embedding = self.get_embedding(dummy_face)

            verification_result = {
                "verified": len(embedding) == self.embedding_size,
                "embedding_shape": embedding.shape,
                "embedding_norm": float(np.linalg.norm(embedding)),
                "model_loaded": self.model is not None,
            }

            if verification_result["verified"]:
                logger.info("FaceNet model verification passed")
            else:
                logger.warning("FaceNet model verification failed")

            return verification_result

        except Exception as e:
            logger.error(f"Model verification failed: {e}")
            return {"verified": False, "error": str(e)}

    @staticmethod
    def compute_similarity(embedding1: np.ndarray, embedding2: np.ndarray) -> float:
        """
        Compute cosine similarity between two embeddings.

        FaceNet embeddings are already L2 normalized, so cosine similarity
        is just the dot product.

        Args:
            embedding1: First embedding vector
            embedding2: Second embedding vector

        Returns:
            Cosine similarity score (0 to 1)
        """
        return float(np.dot(embedding1, embedding2))
